name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull Image
      run: |
        docker pull k8s.gcr.io/kube-proxy:v1.20.2
        docker pull k8s.gcr.io/kube-controller-manager:v1.20.2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Test
      run: |
        docker images
    - name: Rename tag
      run: | 
        docker image tag k8s.gcr.io/kube-proxy:v1.20.2 wallesoft/kube-proxy:v1.20.2
        docker image tag k8s.gcr.io/kube-controller-manager:v1.20.2 wallesoft/kube-controller-manager:v1.20.2
    - name: Push image to DockerHub
      run: |
        docker push wallesoft/kube-proxy:v1.20.2
        docker push wallesoft/kube-controller-manager:v1.20.2
