name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull Image
      run: |
        docker pull k8s.gcr.io/kube-proxy:v1.20.2
        docker pull k8s.gcr.io/kube-controller-manager:v1.20.2
    - name: Test
      run: |
        docker images
