name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull Image
      run: |
        docker pull k8s.gcr.io/kube-proxy:v1.20.2
        docker pull k8s.gcr.io/kube-controller-manager:v1.20.2
        docker pull k8s.gcr.io/kube-apiserver:v1.20.2
        docker pull k8s.gcr.io/kube-scheduler:v1.20.2
        docker pull quay.io/coreos/flannel:v0.13.1-rc1
        docker pull k8s.gcr.io/etcd:3.4.13-0
        docker pull k8s.gcr.io/coredns:1.7.0
        docker pull k8s.gcr.io/pause:3.2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Test
      run: |
        docker images
    - name: Rename tag
      run: | 
        docker image tag k8s.gcr.io/kube-proxy:v1.20.2 wallesoft/kube-proxy:v1.20.2
        docker image tag k8s.gcr.io/kube-controller-manager:v1.20.2 wallesoft/kube-controller-manager:v1.20.2
        docker image tag k8s.gcr.io/kube-apiserver:v1.20.2 wallesoft/kube-apiserver:v1.20.2
        docker image tag k8s.gcr.io/kube-scheduler:v1.20.2 wallesoft/kube-scheduler:v1.20.2
        docker image tag quay.io/coreos/flannel:v0.13.1-rc1 wallesoft/coreos-flannel:v0.13.1-rc1
        docker image tag k8s.gcr.io/etcd:3.4.13-0 wallesoft/etcd:3.4.13-0
        docker image tag k8s.gcr.io/coredns:1.7.0 wallesoft/coredns:1.7.0
        docker image tag k8s.gcr.io/pause:3.2 wallesoft/pause:3.2
        
    - name: Push image to DockerHub
      run: |
        docker push wallesoft/kube-proxy:v1.20.2
        docker push wallesoft/kube-controller-manager:v1.20.2
        docker push wallesoft/kube-apiserver:v1.20.2
        docker push wallesoft/kube-scheduler:v1.20.2
        docker push wallesoft/coreos-flannel:v0.13.1-rc1
        docker push wallesoft/etcd:3.4.13-0
        docker push wallesoft/coredns:1.7.0
        docker push wallesoft/pause:3.2
        
